DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nestjs_app') THEN
    CREATE ROLE nestjs_app LOGIN PASSWORD 'nestjs_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE testdb TO nestjs_app;
GRANT USAGE ON SCHEMA public TO nestjs_app;
